name: Masahito Hayashi's Research Group
url: http://awesome.example.edu
encoding: utf-8

exclude: [pandoc, README.md, Makefile, vscode.code-workspace]

### Conversions
markdown: kramdown
highlighter: pygments # colorize code snippets
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html

# Sections on the "research" page.
researchtypes:
  - key: topic ## research topic
    name: Research Topics
  - key: project ## research topic
    name: Research Projects

# Sections on the "people" page.
roles:
  - key: pi
    name: Principle Investigator
  - key: professor
    name: Researchers
  - key: postdoc
    name: Postdocs
  - key: phd
    name: Ph.D. Students
  - key: master
    name: Master Students
  - key: undergraduate
    name: Undergraduate Students
  - key: collaborator
    name: Collaborators
  - key: visitor
    name: Visitors
  - key: alumni
    name: Alumni

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _research folder
collections:
  researches:
    output: true
  about.md:
    output: true

# Navigation bar links.
navigation:
  - title: HOME
    link: /
  - title: RESEARCH
    link: /research.html
  - title: MEMBERS
    link: /members.html
  - title: PUBLICATIONS
    link: /publications.html
  - title: NEWS
    link: /news.html
  - title: ABOUT ME
    link: /about.html

